### PR TITLE
New Group Finder

### PR DESCRIPTION
**Pull request by delianides**
- tags and search parameters are the same thing and only get parsed when the form is submitted
- tags are basically a modal

### CODE REVIEW

**Comment by richarddubay** [comment]
@delianides this is soooo cool! 🎉 

A few things I think we could do to make it even better:

1. We should make it so that it skips the comma formatting after every word and instead only breaks on tags that it finds as someone is typing. So if I type "kid friendly gaming conventions near me" the search string would end up looking like "kid friendly, gaming, conventions near me". The tags would be set to "kid friendly", "gaming" and the query would be "conventions near me".
2. We should be more forgiving on the typing of tags. Currently, if I type "gaming" it does not recognize that as a tag. "Gaming" on the other hand, works. Either one of those words should trigger the "Gaming" tag and probably auto-capitalize the word to match the tag.
3. Also, the CI was failing because of flow type errors. We should fix those. :)

**Comment by delianides** [comment]
@richarddubay there's now a `readOnly` prop on the `Form.Input`, you can add this to the location field if the user chooses to find their location.

**Comment by delianides** [comment]
@richarddubay @samclaridge to finish this up there are a few outstanding tasks that will need to complete. Feel free to edit this comment or add your own with additional tasks

- [ ] Better modal behavior for tag and campus select fields. This includes fixing the overlay CSS to better cover nearby fields. 
- [ ] `tagOnSelect` needs to be updated to also include location and zip, but only needs to require one of the three to be valid. (Probably needs to be renamed)
- [ ] Location field needs to add the `readonly` prop to make the field read only if we're using geolocation.
- [ ] tabing between the fields needs to be turned off
- [ ] svg icons need to be added to each field using the new SVG component

**Comment by delianides** [comment]
# QA Checklist for iOS

- [x] Sign In
- [x] Giving
- [x] Group Finder
- [x] Feed/Content
- [x] Sharing
- [x] Video Playback
- [x] Audio Playback
- [x] Locations
- [x] Search
- [x] Account Changes
- [ ] Push notifications
- [x] Open in app (dynamic links)
- [x] Live
- [x] Sprint Features - New Group Finder

**Comment by delianides** [comment]
# QA Checklist

- [x] Sign In
- [x] Giving
- [x] Group Finder
- [x] Feed/Content
- [x] Sharing
- [x] Video Playback
- [x] Audio Playback
- [x] Locations
- [x] Search
- [x] Account Changes
- [x] Push notifications
- [x] Open in app (dynamic links)
- [x] Live
- [x] Sprint Features - Group Finder

**Comment by richarddubay** [comment]
# QA Checklist for Kindle

- [ ] Sign In
- [ ] Giving
- [ ] Group Finder
- [ ] Feed/Content
- [ ] Sharing
- [ ] Video Playback
- [ ] Audio Playback
- [ ] Locations
- [ ] Search
- [ ] Account Changes
- [ ] Push notifications
- [ ] Open in app (dynamic links)
- [ ] Live
- [ ] Sprint Features - New Group Finder

**Pull request merged**
