### PR TITLE
Fixes Analytics

### PR DESCRIPTION
**Pull request by JakeDawkins**
- Changed componentWillMount to componentDidMount to fix analytics misreporting

**When I logged out the pathname right before the `ga()` call, it was printing the current path before.**

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://c444054d-2378-4111-bc36-e07898177beb.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzman/branch/fix-analytics/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by jbaxleyiii** [comment]
@JakeDawkins I'm not sure I follow this:

> When I logged out the pathname right before the ga() call, it was printing the current path before.

**Comment by JakeDawkins** [comment]
@jbaxleyiii before, when the analytics code was in `componentWillMount()` I printed out `window.location.pathname`, and it was logging the correct location. Shouldn't the analytics code be reporting the correct thing then?

**Comment by JakeDawkins** [comment]
Logged in
jan-15-2017 14-38-11

Not logged in
jan-15-2017 14-38-22

**Pull request merged**
