### PR TITLE
Reset store on user logout

### PR DESCRIPTION
**Pull request by JakeDawkins**
# Feature / Fixed Issue(s)
- When people log out of their accounts, all data about them should be removed from the local store
- When logging back in, the data should be refetched

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://2f5cde03-6e97-4233-825b-107c677b48cd.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzman/branch/logout-reset-data/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by jbaxleyiii** [comment]
@JakeDawkins this looks great. Do you think you know how to test these changes? If not it's okay! This is a hard one to test and I can walk you through it next week!

**Comment by JakeDawkins** [comment]
@jbaxleyiii Between the data fetching and the redux store testing, I'm fairly certain I'd have no idea. Haha

**Comment by jbaxleyiii** [comment]
haha no worries! @JakeDawkins let's make sure to revisit it next week though 👍. In fact, after this is merged, let's create a WIP PR as a reminder

**Pull request merged**
