### PR TITLE
Small button

### PR DESCRIPTION
**Pull request by JakeDawkins**
How does this look @jbaxleyiii? I'm gonna write tests now, just wanted to make sure I wasn't testing the wrong stuff :) Sam said padding should be `5 15` so I did something similar to the existing buttons to account for the font.

# Feature / Fixed Issue(s)
Added a `<SmallButton/>` component

screen shot 2016-12-04 at 12 41 06 pm
screen shot 2016-12-04 at 12 41 16 pm
screen shot 2016-12-04 at 12 41 22 pm
screen shot 2016-12-04 at 12 41 36 pm

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://00c3a297-4691-47e8-967e-2d20b0756c4c.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzman/branch/small-button/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by jbaxleyiii** [comment]
@JakeDawkins 🔥 looks great!

**Comment by samclaridge** [comment]
@JakeDawkins padding top and bottom should be 5px, but left and right should be 15px. If we are doing set pixel widths. If we're trying to use junction classes we should do soft-half-sides and then we need our quarter class to do push-quarter-sides.

**Comment by JakeDawkins** [comment]
@samclaridge 👍  I was just setting the padding manually because of the font having that small space at the bottom messing up vertical alignment. We don't have a way around that in Junction, right?

**Comment by samclaridge** [comment]
@JakeDawkins no we don't right now, but we've talked about adding it.

**Comment by jbaxleyiii** [comment]
@JakeDawkins can you move this story under the current buttons header?

**Pull request merged**
