### PR TITLE
Release Candidate 4/27 

### PR DESCRIPTION
**Pull request by delianides**
- fixed liked albums in user profile 
- set future send date so forgot password emails send immedately 
- added saved payments back 
- dangerfile.js changes for CI only
- prevent custom dates from use when other filters used 
- fixed tag select --untested 
- added unit-cost for each product to the transaction. 
- added loading state for reviewing checkout 
- added credit-card exp validation 
- removed hockey 
- changed filter click to support switching

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://5bc9bbd0-c54a-45a5-b235-382509cc1b0d.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzman/branch/release-4-27/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by delianides** [comment]
# iOS QA Checklist
- [ ] Sign In
- [ ] Giving
- [ ] Group Finder
- [ ] Feed/Content
- [ ] Sharing
- [ ] Video Playback
- [ ] Audio Playback
- [ ] Locations
- [ ] Search
- [ ] Account Changes
- [ ] Live
- [ ] Sprint Features
- [ ] Live
- [ ] Sprint Features

# Android QA Checklist
- [ ] Sign In
- [ ] Giving
- [ ] Group Finder
- [ ] Feed/Content
- [ ] Sharing
- [ ] Video Playback
- [ ] Audio Playback
- [ ] Locations
- [ ] Search
- [ ] Account Changes
- [ ] Live
- [ ] Sprint Features
- [ ] Live
- [ ] Sprint Features

# Kindle QA Checklist
- [ ] Sign In
- [ ] Giving
- [ ] Group Finder
- [ ] Feed/Content
- [ ] Sharing
- [ ] Video Playback
- [ ] Audio Playback
- [ ] Locations
- [ ] Search
- [ ] Account Changes
- [ ] Live
- [ ] Sprint Features
- [ ] Live
- [ ] Sprint Features

**Comment by delianides** [comment]
@JakeDawkins @jbaxleyiii @richarddubay I fill like #1357 needs to be fixed for this release. Thoughts?

**Comment by delianides** [comment]
Giving is good on each platform and I never had an instance where campus wasn't specified.

**Pull request merged**
