### PR TITLE
Changed group finder filter button

### PR DESCRIPTION
**Pull request by JakeDawkins**
# Feature / Fixed Issue(s)
- Changed group finder filter button from `...` to `filter`
- changed tags to use a `span` inside the markup to allow custom icon classes
- pretested both

# Testing/Documentation
- [ ] All significant new logic is covered by tests.
- [ ] Changelog has been updated.

# Screenshots
screen shot 2017-05-30 at 3 43 50 pm
screen shot 2017-05-30 at 3 43 59 pm

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@JakeDawkins or @richarddubay is this deployed to beta so I can take a look at it in usage?

**Comment by richarddubay** [comment]
@jbaxleyiii I don't believe it is. We weren't sure that you wanted to include this in the current beta of the app since users are testing what we have already. I suppose we could build it and they could have this too if you want.

**Comment by jbaxleyiii** [comment]
@richarddubay we should be able to deploy to beta web without messing up the current beta 🌮 That should allow me to test it out enough

**Comment by jbaxleyiii** [comment]
But I agree, if it is solid, we can include it in the 5.2.0 with some updates we need to make tomorrow

**Comment by richarddubay** [comment]
I'll ship a web beta. Hold please.

**Comment by richarddubay** [comment]
Beta web has been updated. Enjoy. 🎉

**Comment by jbaxleyiii** [comment]
@richarddubay @JakeDawkins on android the text was not centered in the button. Can we take a look at why that may be? (even browsing beta from an android phone did not have them centered)

**Comment by richarddubay** [comment]
screenshot 2017-06-07 17 45 09

@jbaxleyiii I guess maybe I'm not seeing what you're seeing. The text and icons look pretty close to centered to me? This was a screenshot from a Nexus 5S in the Chrome inspector.

**Pull request merged**
