### PR TITLE
Update schedule overview

### PR DESCRIPTION
**Pull request by edolyne**
Do you want to use the <Currency /> component?

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://5cba9b85-6075-4041-ab6f-e9dd1788360e.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzman/branch/update-scheduleOverview/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by jbaxleyiii** [comment]
@edolyne those changes to currency should be on master, can you rebase?

**Comment by edolyne** [comment]
@jbaxleyiii This PR uses the Currency component, rather than the originally written functions inside of cards.ScheduleOverview.js

**Comment by jbaxleyiii** [comment]
@edolyne ah I see, sorry about that 👍

**Comment by edolyne** [comment]
@jbaxleyiii It's all good.

**Pull request merged**
