### PR TITLE
Release Candidate

### PR DESCRIPTION
**Pull request by JakeDawkins**
## Giving Statement Updates
- [ ] Giving statement wasn't showing all time when all time was selected
- [ ] could not switch from one filter to another directly, only by first disabling the active toggle

## Content Loading indefinitely
- [ ] siteLink was trying to access a deeply nested value at the wrong time and was throwing an error, causing the loading spinner to _sometimes_ go on forever

**note**: I couldn't seem to find the caller for this. I saw 2 references to siteLink in the project, and i couldn't get either to actually call, causing an error. This fix solves the problem, but I'm still not 100% sure _why_ it was a problem to begin with 😁

## Fastlane updates
- [ ] updated certs

## QA Process
- [ ] finished QA

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://f9610afa-58aa-4319-86f3-602e66b185d8.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzman/branch/release-4-13/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by delianides** [comment]
- [ ] this is a checkbox

**Comment by JakeDawkins** [comment]
# iOS

- [x] Sign In
- [x] Giving
- [x] Group Finder
- [x] Feed/Content
- [x] Sharing
- [x] Video Playback
- [x] Audio Playback
- [x] Locations
- [x] Search
- [x] Account Changes
**note**: when saving info it says your information has been updated, but it only flashes it for a very short time
- [ ] Live
- [x] Sprint Features

# Web 

- [x] Sign In
- [x] Giving
- [x] Group Finder
- [?] Account Changes
- [x] Sprint Features

**Comment by richarddubay** [comment]
Kindle QA Checklist

- [ ] Sign In
- [ ] Giving
- [ ] Group Finder
- [ ] Feed/Content
- [ ] Sharing
- [ ] Video Playback
- [ ] Audio Playback
- [ ] Locations
- [ ] Search
- [ ] Account Changes
- [ ] Live
- [ ] Sprint Features

**Comment by richarddubay** [comment]
Kindle looks GTG. 💯

**Pull request merged**
