### PR TITLE
Fix Giving Statement

### PR DESCRIPTION
**Pull request by JakeDawkins**
# Feature / Fixed Issue(s)
- Giving statement wasn't showing all time when all time was selected
- could not switch from one filter to another directly, only by first disabling the active toggle

# Testing/Documentation
- [x] All significant new logic is covered by tests.
- [x] Changelog has been updated.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://18f66641-7ac4-41ba-a0b2-09df72543d8a.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzman/branch/fix-statement/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by JakeDawkins** [comment]
@richarddubay @jbaxleyiii there's an accompanying Heighliner PR open [here](https://github.com/NewSpring/Heighliner/pull/304). 

QA [here](beta-my.newspring.cc/give/history)

Change the filters, try printing a statement. The statement should be YTD by default until you change the filters. Then, it should follow the history filter

**Comment by richarddubay** [comment]
@JakeDawkins I still have to look through the code, but wanted to comment. This says that you did some work on making the filter buttons able to be clicked without having to click off of the other one first. This works great. But if I have a filter selected, then I shouldn't be able to click on the custom date filters because they are grayed out. The problem I'm seeing is that I can click on them and choose a date and everything. Maybe take a look at that when you get a second?

BTW, the printing seems to be working really well!

**Comment by JakeDawkins** [comment]
@richarddubay good catch 💯

**Comment by JakeDawkins** [comment]
screen shot 2017-04-13 at 11 51 09 am
screen shot 2017-04-13 at 11 51 53 am

**Comment by JakeDawkins** [comment]
@richarddubay we're waiting until the next spring to fix the issue you mentioned above

**Comment by richarddubay** [comment]
@JakeDawkins Next spring is a long time. But if it's on production now, then that's cool. We should make a task in JIRA @meredithrouse to fix this.

**Pull request merged**
