### PR TITLE
Fix Schedule Toggle

### PR DESCRIPTION
**Pull request by richarddubay**
# Feature / Fixed Issue(s)
- There was a bindSubComponentReset function that was toggling the schedule open and closed whenever something like removing the amount happened. I removed that function to stop it from happening. I tested and it looks like this fixes the problem for most cases. Would love someone to do some extensive testing to make sure I didn't miss something.

# Testing/Documentation
- [x] All significant new logic is covered by tests.
- [x] Changelog has been updated.

### CODE REVIEW

**Comment by jonhorton** [comment]
@richarddubay is this available to test on beta?

**Comment by richarddubay** [comment]
@jonhorton Not yet. But I can put it there. I'll let you know when it's available.

**Comment by richarddubay** [comment]
@jonhorton These changes are on beta-my and in the latest beta app.

**Comment by jonhorton** [comment]
@richarddubay From my tests, this appears to be work properly. Probably worth having @delianides take a peak on the code side once he's back!

**Comment by delianides** [comment]
This is working on my branch too! 👍

**Pull request closed without merging**
