### PR TITLE
Year To Date Component

### PR DESCRIPTION
**Pull request by richarddubay**
# Feature / Fixed Issue(s)
- Year To Date Component

# Testing/Documentation
- [x] All significant new logic is covered by tests.
- [x] Storybook documentation has been added.

# Screenshots
- If applicable, include screenshots of UI/style changes.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://36073453-ca32-41dc-8d8d-aa5c025fa30f.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzman/branch/year-to-date/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by jbaxleyiii** [comment]
@richarddubay this is looking good! A couple comments:

- [ ] Can we make the scatter points larger? Say 5px in diameter?
- [ ] Lets bump up the size of the money section. <h5><h3><h5> ($ INT cents)

Here is an image [link](https://cl.ly/09061Y1l083S)

**Comment by richarddubay** [comment]
@jbaxleyiii @samclaridge How do you guys feel about this?

**Comment by richarddubay** [comment]
screenshot 2016-12-01 15 20 42

Added more padding between the axis and the graph. This feels better and is more readable.

**Comment by samclaridge** [comment]
This looks great. The only thing I'd say to adjust design wise, is the line should be 2px, and the dots 10px. That should alleviate some of the jaggedness of the graph.

**Comment by richarddubay** [comment]
@samclaridge The good news is that those are both props that we can pass into the component to make them whatever we want. I'll update the storybook file for this so that it has the numbers you suggested and will post a new screenshot when it's done.

**Comment by richarddubay** [comment]
screenshot 2016-12-01 16 52 56

Updated lines and dots.

**Comment by richarddubay** [comment]
giphy

**Pull request merged**
