### PR TITLE
Fix activity feed not showing all contributions

### LINKED ISSUE #1649: Gifts to Christmas funds not showing in Activity feed
## Steps to Reproduce

Describe how to reproduce this issue.

1. Go to "Give Now" and give to a fund + give to Christmas feed
2. After you have successfully given, go to the "Home" sub-nav and view the "Activity" feed
3. Look to see if all of your funds are shown

### Buggy Behavior

General fund and Step Up fund show up in Activity Feed, but the Christmas Fund doesn't appear. (All funds, however, appear in History if given to)

### Expected Behavior

All funds that you give to should show up in the Activity feed.

### PR DESCRIPTION
**Pull request by JakeDawkins**
# Feature / Fixed Issue(s)
- resolves #1649 
- I originally was not accounting for the fact that a single transaction can be toward multiple funds, thus the transactionDetails array 👎 . I added a contribution to each `fund` as a single activity in the feed. 
- Another option would be to have a single card with the potential to show contributions to multiple funds, i.e. `Your gift of $1 to General Fund and $0.50 to Christmas Offering was successful`. This would take a little more work, but it would keep one transaction to one card. Thoughts, @jbaxleyiii, @samclaridge ? 
- ALSO, I fixed the precision of non-whole dollar amounts to have two decimal places
- ALSO ALSO what should the blank-state copy say? Right now, its: 
screen shot 2016-12-20 at 4 50 08 pm

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://baf2398d-a0d2-4939-8ed8-b474709e2098.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzman/branch/fix-activity-feed/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by JakeDawkins** [comment]
I added
- support for multiple accounts in one transaction card
- support for passing a react component as the `message` on the activity card (so we can bold stuff, etc)
- a whole bunch of messy string templating logic to support 2 accounts (since that's the max) and  bolding of parts of the sentence.

Here's some screenshots of the updates: 
screen shot 2016-12-20 at 7 17 21 pm
screen shot 2016-12-20 at 7 19 12 pm

**Comment by JakeDawkins** [comment]
I updated the placeholder copy, and added a link to giving. Should the link be a button or link like the other cards? 
screen shot 2016-12-20 at 7 50 21 pm

**Comment by jbaxleyiii** [comment]
@JakeDawkins a button is the better CTA here, lets make it simply `Give Now` and link to /give/now. They may have given in service before so we don't want insinuate they haven't given before. Otherswise this is looking great!

**Pull request merged**
