### PR TITLE
Add Yarn support

### PR DESCRIPTION
**Pull request by richarddubay**
# Feature / Fixed Issue(s)
- Add Yarn support

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://0b81625b-1a2e-406a-8a48-7c706dd0514e.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzman/branch/use-yarn/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by richarddubay** [comment]
screenshot 2016-11-27 08 26 24

@jbaxleyiii 1.17s is pretty legit. And if you pull this branch, the project still runs. Thoughts?

**Comment by jbaxleyiii** [comment]
@richarddubay this is fantastic! Let's go over it in our 1:1 this week 🔥

**Comment by jbaxleyiii** [comment]
@richarddubay after the giving stuff goes live on monday, I'm planning on merging this through so everyone can yarn away!

**Comment by richarddubay** [comment]
giphy

**Pull request merged**
